# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

filter: 'category'
# author information
author:
  name: 紫无之紫
  email: 15381158111@163.com
  github: https://github.com/cstarc

  
# Site settings
title: 紫无之紫的博客  
description: > # this means to ignore newlines until "baseurl:"
    记录学习经历
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cstar.github.io" # the base hostname & protocol for your site

github_username:  cstar




# avatar头像及Favicon
avatar: /assets/images/me.jpg
favicon: /assets/img/me.ico

sass:
  style: compressed
gems:
  - jekyll-sitemap
